services:
  db:
    image: mysql:latest
    container_name: mymysql_container
    environment:
      MYSQL_DATABASE: vanger
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: